test:
#  url: 192.168.88.130
  url: 18.216.46.202
#  path: /home/cat
  path: /img
  vue: 18.216.46.202


spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/feed?sueSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    url: jdbc:mysql://118.67.133.148:3306/feed?sueSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://database-1.cndbyzmembzk.us-east-2.rds.amazonaws.com:3306/feed?sueSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    password: 12345678
    username: root
#    username: sample
  jpa:
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ShinTest94@gmail.com
    password: aiosjkbzvbxerxya
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


server:
  address: 0.0.0.0
  port: 8888


